version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.8

jobs:
    python-3-8: &test-template
        docker:
            - image: cimg/python:3.8.20-browsers
              auth:
                username: dashautomation
                password: $DASH_PAT_DOCKERHUB

        environment:
            PERCY_ENABLE: 0

        steps:
            - checkout

            - browser-tools/install-browser-tools:
                install-firefox: false
                install-geckodriver: false

            - run:
                name: ✍️ Write job name.
                command: echo $CIRCLE_JOB > circlejob.txt

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

            - run:
                name: 🏗️ Create venv
                command: |
                    python -m venv venv

            - run:
                name: 🏗️ Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - venv

            - run:
                name: 🧪 Generations tests
                command: |
                    . venv/bin/activate
                    pytest
                when: always

    python-3-12-install-test:
        docker:
            - image: cimg/python:3.12.7-browsers
              auth:
                username: dashautomation
                password: $DASH_PAT_DOCKERHUB

        environment:
            PERCY_ENABLE: 0

        steps:
            - checkout

            - browser-tools/install-browser-tools:
                install-firefox: false
                install-geckodriver: false

            - run:
                name: ✍️ Write job name.
                command: echo $CIRCLE_JOB > circlejob.txt

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}

            - run:
                name: 🏗️ Create venv
                command: |
                    python -m venv venv

            - run:
                name: 🏗️ Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "circlejob.txt" }}-{{ checksum "tests/requirements.txt" }}-{{ checksum ".circleci/config.yml" }}
                paths:
                    - venv

            - run:
                name: 🧪 Generate Project & test
                command: |
                    . venv/bin/activate
                    mkdir test_install
                    cd test_install
                    cookiecutter .. --config-file ../tests/test_config.yaml --no-input
                    cd test_component
                    python -m venv venv
                    . venv/bin/activate
                    pip install -r tests/requirements.txt --quiet
                    npm install --ignore-scripts
                    npm run build
                    pytest


workflows:
    version: 2
    build:
        jobs:
            - python-3-8:
                context: dash-docker-hub
            - python-3-12-install-test:
                context: dash-docker-hub
